### PR TITLE
chore: test failures

### PR DESCRIPTION
**Pull request by dancesWithCycles**
Hi folks,
Thank you so much for providing and maintaining this repository. Kudos!

Do you mind me asking some questions?

Why is the issue page missing for this repository?

What Java version are you using?

I am neither a Java nor a Maven expert. Does the following config from the pom.xml file indicate you are using Java 11?

```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.10.0</version>
                <configuration>
                    <source>11</source>
                    <target>11</target>
                </configuration>
            </plugin>
```
I do not have Java 11 available at the moment. I'll touch base and keep you in the loop.

Anyhow, with Java 17 available at the moment and calling ```mvn clean package``` on the master branch, I'll receive the following test failure. 

```
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   EstimatedTimetablesTest.testGetAllMonitored:528 » NullPointer
[ERROR]   EstimatedTimetablesTest.testServiceDeliveryWithPreviewInterval:435 » NullPointer
[INFO] 
[ERROR] Tests run: 403, Failures: 0, Errors: 2, Skipped: 8
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:46 min
[INFO] Finished at: 2022-08-31T22:24:44+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project anshar: There are test failures.
```

Have you made such observations in the past?

Cheers!

### CODE REVIEW

**Comment by dancesWithCycles** [comment]
Hi folks,
I updated the master branch today. Invoking ```mvn clean package``` shows one error less than yesterday. Are you actively working on those issues or is this an accidental observation.

```
 [INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   EstimatedTimetablesTest.testCreateServiceDelivery:384 expected: <true> but was: <false>
[INFO] 
[ERROR] Tests run: 403, Failures: 1, Errors: 0, Skipped: 8
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:57 min
[INFO] Finished at: 2022-09-01T11:00:43+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project anshar: There are test failures.
```

Cheers!

**Comment by lassetyr** [comment]
The issues-feature was just not enabled - it is available now.

We are using Java 17 - the pom.xml is just a bit outdated. 

This repo is under active development, and sometimes we slip up and commit code that causes tests to fail. I just ran `mvn clean package` locally, and I can build this successfully:

```
[INFO] Results:
[INFO] 
[WARNING] Tests run: 403, Failures: 0, Errors: 0, Skipped: 8
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:21 min
[INFO] Finished at: 2022-09-01T15:16:17+02:00
[INFO] ------------------------------------------------------------------------
```

Du you still get the error on your side?

**Comment by dancesWithCycles** [comment]
Hi Lasse @lassetyr ,
Thx for the changes. After pulling them and running

```
mvn clean package -Dmaven.test.skip=true
java -jar target/anshar-0.0.1-SNAPSHOT.jar
```

Anshar was launched and running. Eventually I observed that the port ``8012`` was not served by the Java process. With ``` >> log.txt 2>&1``` I created the following log file.

[log.txt](https://github.com/entur/anshar/files/9470146/log.txt)

That log file contains several error messages I can not classify at the first glimpse. Does those errors make any sense to you?


BTW, I still do not see the 'issue' feature. I'll touch base about the result of ```mvn clean package```.

Cheers!

**Comment by dancesWithCycles** [comment]
> BTW, I still do not see the 'issue' feature. I'll touch base about the result of `mvn clean package`.

Now the `issue` feature appeared. Cheers mate!

**Comment by dancesWithCycles** [comment]
Hi Lasse @lassetyr ,
Except of the skipped tests everything is running through.

```
[INFO] Results:
[INFO] 
[WARNING] Tests run: 403, Failures: 0, Errors: 0, Skipped: 8
```

```
[WARNING] Rule 1: org.apache.maven.plugins.enforcer.RequirePluginVersions warned with message:
Some plugins are missing valid versions or depend on Maven 3.6.3 defaults: (LATEST RELEASE SNAPSHOT are not allowed)
org.apache.maven.plugins:maven-site-plugin. 	The version currently in use is 3.3 via default lifecycle bindings
```

```
[INFO] BUILD SUCCESS
```

Anyhow, the port `8012` is still not served. Here is the log.

[log-2.txt](https://github.com/entur/anshar/files/9470298/log-2.txt)

Is there something I can support you with this issue?

**Comment by lassetyr** [comment]
It seems to be an issue with som Google libraries that require an environment-variable to be set - even if the default configuration switches this functionality off.

I'll try to create a workaround.

**Comment by lassetyr** [comment]
I have added a dummy-credentials file and instructions on how it should be configured (https://github.com/entur/anshar/commit/b555e6e6f4925bc97230a920821e464e8f095ea0).

Does this solve the issue?

**Comment by dancesWithCycles** [comment]
Hi Lasse @lassetyr ,
Issue solved!

`Anshar` is running and port `8012` is served and I can request the stats page ```http://localhost:8012/anshar/stats```.

Thank you so much for your support!

Do you mind me asking a related question?

Is it ordinary behavior that `Anshar` is complaining about missing files like this?

```
...
java.io.FileNotFoundException: mapping_data/jbv_code_mapping.csv (No such file or directory)
...
java.io.FileNotFoundException: mapping_data/quay_mapping.csv (No such file or directory)
...
java.io.FileNotFoundException: mapping_data/stop_place_mapping.csv (No such file or directory)
...
java.io.FileNotFoundException: mapping_data/stop_place_quays.json (No such file or directory)
```

You can find all `Anshar` output in the following log file.

[log-sep-02-2022.txt](https://github.com/entur/anshar/files/9475898/log-sep-02-2022.txt)

Cheers!

**Comment by lassetyr** [comment]
These are files used for some internal id-mappings done for _some_ SIRI-providers in Anshar.

I have now removed them from the default config.

**Comment by dancesWithCycles** [comment]
Cheers mate!

**Pull request closed without merging**
